apiVersion: v1
kind: ConfigMap
metadata:
  name: lakehouse-config
  namespace: cdc-lakehouse
data:
  ICEBERG_REST_URI: http://iceberg-rest:8181
  WAREHOUSE: s3://lakehouse/warehouse
  KAFKA_BOOTSTRAP_SERVERS: broker:29092
