connector.name=iceberg
iceberg.catalog.type=hadoop
hive.metastore.catalog.dir=s3a://lakehouse/warehouse
fs.native-s3.enabled=true
s3.endpoint=http://minio:9000
s3.path-style-access=true
s3.aws-access-key=admin
s3.aws-secret-key=password
s3.ssl.enabled=false
